UPSTREAM: ubsan: fix unused variable warning in test module
This is one of the drivers with an unused variable that is marked 'const'.
Adding a __used annotation here avoids the warning and lets us enable
the option by default:

lib/test_ubsan.c:137:28: error: unused variable 'skip_ubsan_array' [-Werror,-Wunused-const-variable]

Bug: 254441685
Fixes: 4a26f49b7b3d ("ubsan: expand tests and reporting")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240403080702.3509288-3-arnd@kernel.org
Signed-off-by: Kees Cook <keescook@chromium.org>
(cherry picked from commit bbda3ba626b9f57ff6063058877eca856f5b734d)
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I983f90764f748c9fa747287703ba5219e6cc9ad8